name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      placeholder: "e.g. macOS 14.2 Sonoma"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: Tell us what went wrong.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      placeholder: What should have happened instead.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Open Marcus Sync
        2. Go to Settings
        3. ...
    validations:
      required: false

  - type: dropdown
    id: format
    attributes:
      label: Output format
      options:
        - Emoji
        - Dataview
        - Kanban
        - Not related to format
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, log output, or anything else helpful.
    validations:
      required: false
