name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      placeholder: "e.g. macOS 14.2 Sonoma"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: Tell us what went wrong.
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, log output, or anything else helpful.
    validations:
      required: false
