name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for Marcus Sync? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or frustration.
      placeholder: "I wish Marcus could..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your ideal solution
      description: How would this work from a user's perspective?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Sync behavior
        - Output format
        - Settings / UI
        - Menu bar
        - Onboarding
        - Other
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, mockups, or references to similar features.
    validations:
      required: false
